language: go
go:
  - 1.8.x

install:
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/context
  - go get github.com/tinylib/msgp/msgp
  - go get github.com/klauspost/reedsolomon

script:
  - src/test.sh

after_success:
  - bash <(curl -s https://codecov.io/bash) -t 7f41f947-d180-4c3f-8ce0-17a9f01205d3
