language: go
go:
  - 1.8.x

install:
  - go get github.com/gorilla/mux
  - go get github.com/gorilla/context
  - go get github.com/tinylib/msgp/msgp

#script:
 # - src/test.sh

#after_success:
  #- bash <(curl -s https://codecov.io/bash)
